services:
  postgres:
    restart: always
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      # Postgres DB Super User Password
      # Replace the below with your own secure password & Make sure the password matches the password field in DATABASE_URL above
      - POSTGRES_PASSWORD=postgres

  formbricks:
    restart: always
    image: ghcr.io/formbricks/formbricks:latest
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - uploads:/home/nextjs/apps/web/uploads/
    : *environment

volumes:
  postgres:
    driver: local
  uploads: