services:
  note-mark:
    image: ghcr.io/enchant97/note-mark-aio:0.13.1
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      # !!! REPLACE These !!!
      JWT_SECRET: "bXktc2VjcmV0"
      CORS_ORIGINS: "http://example.com:8000"
    ports:
      - 8000:8000