services:
  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - TZ=America/New_York # Set the time zone (optional)
    restart: unless-stopped